### ISSUE TITLE
Mangahere chapters showing extra (non-existant) page in app

### ISSUE THREAD

**Issue by AerosAtar** [inorichi/tachiyomi#1050]
- Version: r1262+ (confirmed)

## Steps to reproduce
1. Open app.
2. Open Mangahere source.
3. Open chapter.
  a. Note page count.
  b. Open chapter in browser.
  c. Note page count (2 page difference in r1262, 1 page difference in r1264).
  d. Browse to final page in app.
  e. Page fails to load.
4. Attempt to download chapter in app.
  a. Note page count in download list.
  b. Download fails at page (pagecount - 1)/pagecount.

## Example
Hajimete no Gal, chapter 42 (https://www.mangahere.co/manga/hajimete_no_gal/c042/)
- Page count on mangahere.co: 19.
- Page count in app: 21 (r1262) / 20 (r1264).
- Download fails at page: 20/21 (r1262) / 19/20 (r1264).

**Comment by AerosAtar** [comment]
Re-tested with r1254 and also seeing the same issue with this build, which was previously working fine,

Potentially a change on mangahere's end has affected this?

**Comment by qwertyuser1983** [comment]
Happen to me too. :(

**Comment by stardeath** [comment]
a "featured.html" with products have been added to the end of each chapter.

**Comment by AerosAtar** [comment]
Unfortunately, unless there is something I need to do in addition to just upgrading to r1267 (which should include this fix), this hasn't fixed this issue.

**Comment by NoodleMage** [comment]
Weird. I tested it and it works fine for me now. Did you check about to be sure you're on the newest version?

**Comment by AerosAtar** [comment]
About is definitely showing r1267, build time 5 Nov 2017 09:43.

Do I need to do some kind of refresh on my library / the chapter lists or something?

**Comment by AerosAtar** [comment]
I did a completely fresh install, and did not see the problem.

I then restored my library from a backup, and again do not see the problem.

The issue itself has been fixed, but it seems there is some kind of caching that is preventing existing installs from updating the page counts. Maybe a 'forced catalogue refresh' of some kind is needed?

**Comment by RatchetNine76** [comment]
Is there a download/patch for this fix? Because I can't seem to find it nor how to.

**Comment by rhuynh20** [comment]
I did an uninstall and a fresh install of r1267 and I still have the problem.
