### ISSUE TITLE
Updating error on readmanga.me

### ISSUE THREAD

**Issue by KirRoil** [inorichi/tachiyomi#1455]
App version: r1418
Error while updating "Noblesse" from http://readmanga.me/noblesse
![photo_2018-05-20_18-44-27](https://user-images.githubusercontent.com/30603434/40888794-37a4686e-6765-11e8-9360-ef0c769da97b.jpg)

**Comment by einstein95** [comment]
Fixed by #1459

**Comment by KirRoil** [comment]
No it's not fixed. I updated everything that can be updated in app settings, but bug is still here

**Comment by CarlosEsco** [comment]
You swipe down in chapter list to refresh it?

**Comment by Taumer** [comment]
@KirRoil it's not fixed in app because #1459 is not merged.
You can install extension for Readmanga. It has already been updated.
