### ISSUE TITLE
[BUG] Single Page Chapter Tracking Update

### ISSUE THREAD

**Issue by bbtora** [inorichi/tachiyomi#2113]
**App version:**
0.8.4-1518
**Android version:**
9
**Issue/Request:**
Concerns #2044 
Reading consecutive single page chapters of a manga and exiting the reader after a certain amount of chapter doesn't update the service tracker with the last read chapter.
This behavior is not observed when reading only one chapter.

**Other Details**
Have not tested with small number of chapters, for example: 2 or 3 consecutive chapters.

**Comment by arkon** [comment]
I _think_ this was addressed by https://github.com/inorichi/tachiyomi/commit/15f225537ec1ea67939002b12f6ad61920f2709e

**Comment by bbtora** [comment]
Umm no, I'm still facing this issue.

**Comment by pervertkirito** [comment]
> Umm no, I'm still facing this issue.

Are you on stable v0.8.4?
This should be fixed in Dev build

**Comment by bbtora** [comment]
On dev build, checked a few days ago and the issue still exists.
