### ISSUE TITLE
Covers not working when source is KissManga

### ISSUE THREAD

**Issue by ruudschouten** [inorichi/tachiyomi#308]
Covers don't work for any title in KissManga.
On other sources they work just fine.

Version: r725
OS: CyanogenMod 13

**Comment by inorichi** [comment]
Two solutions:

1) Update manga details from the info tab by pulling down.
2) Clear database under advanced tab (it will fix only non-favorite manga, those can only be fixed with option 1).

**Comment by ruudschouten** [comment]
2 fixed it. Cheers

**Comment by ruudschouten** [comment]
This actually only works on Manga not in my library, all the ones that I added to My Library still don't have a cover. I tried making a backup, clearing data and restoring, but the covers were still missing.

**Comment by ruudschouten** [comment]
I guess the first method works for this, but it's quite a pain to update every Manga in my library
