### ISSUE TITLE
[Bug] <Reading in webtoon mode isn't perfect in new versions of tachiyomi>

### ISSUE THREAD

**Issue by jorel221** [inorichi/tachiyomi#4052]
## Device information
* Tachiyomi version:  0.10.5
* Android version: 9
* Device: Samsung Galaxy J5 2016 J510MN

## Steps to reproduce
1. install tachiyomi and change reading mode to webtoon
2. find and download a manga or webtoon (without very long stips)
3. start reading and keep scrolling with normal speed
4. pay attention at the bottom of the screen when it's changing pages

### Expected behavior
next page loads without showing the background.

### Actual behavior
sometimes when changing to the next page it shows the backgroud color (black or white), for less than a second until the next page is ready.

## Other details
This problem only occurs with versions that came out after 0.7.4. Version 0.7.4 (or older) and all forks based on it simply don't have this bug, (they have if it's a very long webtoon strip but it's easy to fix by slicing with Photoscape). 0.7.5 and all versions that came out after that have this bug. It happens with mangas as well so it's not a height or color problem. I've also tried to save the pages in different types (jpg png, webp) but it didn't solve this problem. The only problem with 0.7.4 is it doesn't have all the features and changes of the new versions.

**Comment by joseph619** [comment]
That's the buffer page, you can disable it in More > Settings > Reader and disable `Always show chapter transition`.

**Comment by scb261** [comment]
@joseph619 I think it's problem with displaying very long pages, I also have the same problem sometimes, needs some time to load. Related issue #1908

**Comment by jorel221** [comment]
I will try to make a video comparing 0.7.4 and other versions. The new versions have problems loading the next pages (sometimes) even with short strips or manga pages. I've tried to slice in many different heights (200, 300, 500...) but it still happens.

**Comment by jorel221** [comment]
Here's a short video comparing version 0.10.5 r2815 and 0.7.4, I used Solo Leveling on Mangadex as example. I'm starting with ch 1 because ch 0 has long strips so the pages will load slow in both versions. The bug occurs when changing pages 6 to 7 and 11 to 12 (I marked the time in the cooments). I switch to 0.7.4 at 1:28.
https://youtu.be/L-a24HzCUsw

**Comment by Silvermane06** [comment]
Old issue but still open so sorry for necro'ing, I'm 99% sure that's just because the page hadn't fully loaded from the server yet, and just so happens to load as you get to it. Hence a quick flash of black. It happens all the time to me on extensions with slow servers/rate limits, but is even worse due to the fact that the exceptionally slow servers will just show a loading page for a couple seconds (black page + blue ring).

**Comment by jorel221** [comment]
Yes but I'm reading offline, the chapters are stored on my phone so there's no server in question. This problem shouldn't be happening with local or downloaded chapters unlless the page is a long strip. After some tests I found out this only happens BECAUSE I'm reading a downloaded chapter, the problem doesn't happen when reading online, unless slow server, bad conection, long strips, etc.

**Comment by Silvermane06** [comment]
Ah ok, i totally misread that lmfao, sorry.

**Comment by Radiantguled** [comment]
Did anyone find a solution to this problem

**Comment by Shamicen** [comment]
This may be a little naive but couldn't this be fixed by simply displaying the current and the next page instead of only the current page for webtoon and continuous vertical? Or is that simply not possible with the way Tachiyomi works?

**Comment by teresch-a** [comment]
Bug still present on last version. Here is a video example of this bug. [https://user-images.githubusercontent.com/79324308/228976470-9e815fae-4dee-4ab4-9b95-b2578a91a10f.mp4](https://user-images.githubusercontent.com/79324308/228976470-9e815fae-4dee-4ab4-9b95-b2578a91a10f.mp4) 
This seems to be not the problem with long pages, as this is Webtoons.com slicing and every page height is really small.
As previously said, the glitch causes background leak at the bottom of the screen. With so small slices this glitch just too noticable and webcomic mode is unusable. 
Also, the possible cause can be that I'm reading webcomic from .cbz.
