### ISSUE TITLE
Update Loop

### ISSUE THREAD

**Issue by Soumatan** [inorichi/tachiyomi#517]
Tachiyomi is stuck in a infinite loopwhenever I update but I can cancel it. It registers the new chapters but it wont end it just starts from the beginning.

Version: r931
I'm running Moto X with a custom rom called Dirty Unicorn. Android 6.0.1

**Comment by inorichi** [comment]
Should be fixed now, but the build server won't be up for the next 2 hours.

**Comment by Soumatan** [comment]
It's working fine right now.  Will keep testing and let you know if I still see the problem.

**Comment by Soumatan** [comment]
Loop is still there. Did update library just now and the loop started.

**Comment by inorichi** [comment]
Can you paste a logcat?

**Comment by Soumatan** [comment]
Tried creating a logcat with Catlog but had trouble with gaining root access. Because of this  and another problem I was encountering with the rom I changed the rom to a newer one and the problem is not occouring right now. Sorry for the problem and thank you for you hard work.

**Comment by inorichi** [comment]
You don't really need to go through the trouble of rooting. `adb logcat` from your PC and that's all.

Installing Android Studio makes it even easier, but it's a large download.

I'm actually worried of this happening on some ROMs. Was r931 the first installation in the device? Or was it installed previously and you noticed it after the upgrade?
