### ISSUE TITLE
Tachiyomi doesn't display any image files

### ISSUE THREAD

**Issue by Nyoroon** [inorichi/tachiyomi#689]
Tachiyomi doesn't display any image files with any renderer (just shows white background), but downloads and caches them (i can open them in file explorer).
On MIUI 8.1 and Android 5.0 everything was ok.

Version: r1106 and 0.4.1
MIUI 8.0.4.0 Android 6.0

**Comment by inorichi** [comment]
Have you tried all the image decoders?

**Comment by Nyoroon** [comment]
After phone update (and android version update). Was xiaomi redmi 3, now xiaomi redmi note 4.

**Comment by inorichi** [comment]
Do you have crop borders enabled?

**Comment by Nyoroon** [comment]
Disabled.

**Comment by Nyoroon** [comment]
With crop borders enabled
![with crop borders enabled](https://cloud.githubusercontent.com/assets/182203/23102072/57a5b4ac-f6b3-11e6-946b-5dbd360935b9.png)

**Comment by inorichi** [comment]
Well... that's weird, I don't have any clue. Do you get any difference when changing all the available fit modes?

Can you install and test with [this app](https://play.google.com/store/apps/details?id=com.davemorrissey.labs.subscaleview.sample)?

**Comment by Nyoroon** [comment]
All fit modes is same.
In that app all images is badly displayed except "Configuration" section starting from 2nd example.
![](https://lh5.googleusercontent.com/BWNLET70KikTk-trAMDiLOHN18crxXsdHYv6BfeHFpexbR41yovMeQyFm_eNw-kGBJxDmhfLnICejdA=w1920-h971)

**Comment by inorichi** [comment]
I think the values returned by `getResources().getDisplayMetrics()` are wrong.
Can you get a screenshot of this app I just created? [display.zip](https://github.com/inorichi/tachiyomi/files/786117/display.zip) Rename it to .apk (Github doesn't allow to post an apk here)

**Comment by Nyoroon** [comment]
https://drive.google.com/file/d/0B6v8KpkMuQ4bcVBhS3dQM2VhSWc/view

**Comment by inorichi** [comment]
According to Xiaomi, there are 0.403 pixels per inch. Very well done, Xiaomi.

![firefox_2017-02-19_20-59-41](https://cloud.githubusercontent.com/assets/3521738/23105907/6015bee2-f6e6-11e6-8b16-2a31f40d2ab8.png)

This is what should be returned. _Sigh_, I could workaround it when the value is < 1. But this should be fixed by them.

**Comment by Nyoroon** [comment]
MIUI update will come tomorrow (or next week), so maybe they fixed it %)

**Comment by Nyoroon** [comment]
Fixed in new firmware, so i closing ticket.

**Comment by kikuKeii** [comment]
I am currently still having this problem ,If I download comic, sometimes it only shows the background. It doesn't seem like a display pixel or firmware issue. Because I solved this problem by restarting my smartphone. Is there any other way besides restarting?

**Comment by joseph619** [comment]
Open a new ticket, this issue is over 3 years old and was ogiianlly resolved
