### ISSUE TITLE
Kissmanga page list is emptg for over a week

### ISSUE THREAD

**Issue by Sinnesfrid** [inorichi/tachiyomi#722]
Running 5.0 earlier and now 5.1
Been logging into kissmanga and confirmed I am not a robot 
Waited and tried daily for the past week but still it keeps showing up with page list empty

**Comment by dahlys** [comment]
Same problem here. Running 5.1

**Comment by iBaer** [comment]
Did you try the various things at "settings" -> "advanced" yet?
I don't have any problems since using 0.5.1

**Comment by dahlys** [comment]
Tried everything in advanced. Still not working. I get the message "page list is empty".

**Comment by GreyAsteroid** [comment]
If your IP isn't CAPTCHA locked then it's a side effect of the issue that was fixed with 5.1. 
"Settings > Advanced > Clear chapter cache" should clear out bad cache created on 5.0.
If this doesn't work then backing up your settings, clearing Tachiyomi's app data, then restoring your settings should make sure that nothing bad from 5.0 is lurking around anymore. 

If none of this works then your IP is most likely CAPTCHA locked and you're not being given the CAPTCHA due to your browser or something on KissManga's side (it's happened to me before). There's also the possibility that KissManga's servers are acting up, though this usually doesn't just happen for a few people.

**Comment by dahlys** [comment]
Cleared cache and app data. Still not working. Kissmanga loads fine on the browser.

**Comment by GreyAsteroid** [comment]
Double check that you are in fact on 0.5.1 and then confirm that you can reproduce the error on a different IP, i.e., Using mobile data instead of your local network or vice versa.

**Comment by dahlys** [comment]
Okay it works on public wifi but not my home/school internet. I don't have mobile data. How do I get the ip address unblocked?

**Comment by GreyAsteroid** [comment]
Usually going to the website and loading a chapter will give you a CAPTCHA to solve, so try loading [this](http://kissmanga.com/Manga/Pineapple-Army/Pineapple-Army-Chapter-9?id=49895).
Try on a computer and on your device. If you're using Chrome on your device try it in desktop mode as well.

**Comment by dahlys** [comment]
It works! Thanks guys!

**Comment by Sinnesfrid** [comment]
Still not working for me, oddly enough so does it only affect the latest chapter and not all chapters now.and when a new one comes out so is the old one working.
